# Generated by Django 4.2.9 on 2026-01-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Life Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('', '—'), ('Idea', 'Idea'), ('Journey', 'Journey'), ('Project', 'Project'), ('Action', 'Action')], default='', max_length=20)),
                ('action_length', models.CharField(blank=True, choices=[('', '—'), ('5 minutes', '5 minutes'), ('15 minutes', '15 minutes'), ('1 hour', '1 hour'), ('3 hours', '3 hours')], default='', max_length=20)),
                ('time_frame', models.CharField(blank=True, choices=[('', '—'), ('Now', 'Now'), ('Today', 'Today'), ('This Week', 'This Week'), ('This Month', 'This Month'), ('Future', 'Future')], default='', max_length=20)),
                ('value', models.IntegerField(blank=True, choices=[(None, '—'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(None, '—'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Complete', 'Complete'), ('Archive', 'Archive'), ('Remove', 'Remove')], default='Open', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('life_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.lifecategory')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
